### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Codeusa** [AurousGroup/frontend#2]
This is a running TODO list of noted bugs or features we need to implement. 
- [ ] Optimize local song loading; decrease UI lag and support thousands of songs being loaded
- [ ] Optimize source code/rebuild on a framework (Angular is the running leader)
- [ ] Playlist
- [ ] Social integration with VK for searching 
- [ ] Fix lag when loading a fresh db/large table, also goes with step 1
- [ ] Add progress for downloads

**Comment by kz-lt** [comment]
Maybe look into React+Flux? It could most likely perform better than Angular in most cases.

**Comment by Codeusa** [comment]
We're porting to reactjs

**Comment by Nickforall** [comment]
What about multilingual support?

**Comment by franklinjavier** [comment]
+1 for ReactJS

**Comment by gabrielbiga** [comment]
What do you think of these goals for the future?

1. Use Bower to manage the frontend deps
2. Replace the HTML -> Jade for more easy markup
3. Put a JavaScript language with sugar (like TypeScript or CoffeeScript) manage more easily classes and modules
4. Browserify to manage the frontend modules
5. A CSS preprocessor like Less, Sass or Stylus
6. Gulp or Grunt to build all

I think we need all this items to get a better software.

**Comment by Anfa-am** [comment]
@gabrielbiga I +1 all your points except the use of type/coffeescript. We shouldn't be working towards segregating ourselves from the majority of the JS community. A much more endurable solution to handling classes and modules would be to move towards es6.

**Comment by qrenz** [comment]
tablejs for organization / alphabetical order?

**Comment by qrenz** [comment]
Would it be more wise just to wait for you guys to port to reactjs until i start improvements?

**Comment by danjford** [comment]
Or instead of react perhaps consider using ractivejs and instead of using bower maybe just use npm to manage dependencies.

**Comment by danilobrinu** [comment]
What do you think of these goals for the future?

* **Bower** to manage frontend dependencies, is better option.
* **Browserify** to modularize scripts, is the best.
* **Gulp** to automate workflow
* Port all scripts to **ES6 with Babelify** (Support React and JSX)
* Abstract the main funcionality to manage audio
* Separate visual components with respective react components
* Use **RAIL Model** to create a visual impact and performace (see http://www.smashingmagazine.com/2015/10/rail-user-centric-model-performance/)
* Use javascript testing framework like **Mocha and Chai** or **Karma**
* Use **Flexbox** to design all components of the frontend
* Integrate a easy plugin manager
* Remove innecesary libraries

**Comment by borisrorsvort** [comment]
I'd would highly recommand using [webpack](https://webpack.github.io/) instead of browserify and bower.

**Comment by luigiplr** [comment]
FYI some of this has already been made @ https://github.com/AurousGroup/frontend/tree/feature/react

**Comment by borisrorsvort** [comment]
:cry:  though :+1:  for using alt.js as the flux implementation :smile:
